# Generated by Django 4.0 on 2022-07-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
