# Generated by Django 4.0 on 2022-07-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_plans_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='dongle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=20)),
                ('dprize', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='postpaid',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pstname', models.CharField(max_length=20)),
                ('pstprize', models.IntegerField()),
            ],
        ),
    ]
