# Generated by Django 4.0 on 2022-07-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_customer_newconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('plan_name', models.CharField(max_length=20)),
                ('month', models.IntegerField()),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
